# -*- coding: utf-8 -*-

# PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
# https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code

from ccxt.async_support.acx import acx


class wadax (acx):

    def describe(self):
        return self.deep_extend(super(wadax, self).describe(), {
            'id': 'wadax',
            'name': 'Wadax',
            'countries': ['EU'],
            'has': {
                'CORS': False,
            },
            'urls': {
                'logo': 'https://user-images.githubusercontent.com/1294454/45444675-c9ce6680-b6d0-11e8-95ab-3e749a940de1.jpg',
                'extension': '.json',
                'api': 'https://wadax.io/v2',
                'www': 'https://wadax.io',
                'doc': 'https://wadax.io/doc/api',
            },
        })
