<?php
namespace ccxt;
// PLEASE DO NOT EDIT THIS FILE, IT IS GENERATED AND WILL BE OVERWRITTEN:
// https://github.com/ccxt/ccxt/blob/master/CONTRIBUTING.md#how-to-contribute-code
use Exception as Exception; // a common import
class wadax extends acx {
    public function describe () {
        return array_replace_recursive (parent::describe (), array (
            'id' => 'wadax',
            'name' => 'Wadax',
            'countries' => array ( 'EU' ),
            'has' => array (
                'CORS' => false,
            ),
            'urls' => array (
                'logo' => 'https://user-images.githubusercontent.com/1294454/45444675-c9ce6680-b6d0-11e8-95ab-3e749a940de1.jpg',
                'extension' => '.json',
                'api' => 'https://wadax.io',
                'www' => 'https://wadax.io',
                'doc' => 'https://wadax.io/doc/api',
            ),
        ));
    }
}
